version: "3"

services:

  revers:
    build: ./revers
    ports: 
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M
        reservations:
          cpus: '0.15'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 7s
        max_attempts: 2
        window: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "15"

  zoopark:
    # После конечного одобрения убрать билд с докерфайла
    #image: sanpilogov161/zoopark:latest
    build: ./flask
    depends_on:
      - revers
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 15M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "7"

  speedtest:
    build: ./speedtest
    depends_on:
      - revers
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 15M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "7"

      