version: "3"

services:
  flask:
    container_name: zoopark # Это лишнее, лучше перенести это в название сервиса
    image: sanpilogov161/zoopark:latest
    # Тут нужен блок с политикой перезапуска сервиса
    # Тут добавить healthcheck
    # Тут нужен блок описывающий политику ведения логов
    # тут должен быть блок resources

  testspeed:
    container_name: speed-site # Это лишнее
    build: ./speedtest
    # Тут нужен блок с политикой перезапуска сервиса
    # Тут добавить healthcheck
    # Тут нужен блок описывающий политику ведения логов
    # тут должен быть блок resources

  revers:
    container_name: revers # Это лишнее
    build: ./revers
    ports: 
      - 80:80
    links: # Это лишнее
      - "flask" # Это лишнее
      - "testspeed" # Это лишнее
    # Тут нужен блок с политикой перезапуска сервиса 
    # тут должен быть блок resources
    # Тут нужен блок описывающий политику ведения логов
      

      
## Нужно добавить блоки depends_on для сервисов
