version: "3"

services:
  flask:
    container_name: zoopark
    image: sanpilogov161/zoopark:latest

  testspeed:
    container_name: speed-site
    build: ./speedtest

  revers:
    container_name: revers
    build: ./revers
    ports: 
      - 80:80
    links:
      - "flask"
      - "testspeed"
