#Old
## TODO: Может поискать официальный образ? А еще лучше - самому собрать необходимое в alpine
#FROM jazzdd/alpine-flask 
#RUN pip install emojis
#COPY ./app.py .
#EXPOSE 80
# syntax=docker/dockerfile:1.4
FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder

WORKDIR /src
COPY requirements.txt /src
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . .
RUN pip install emoji
CMD ["python3", "app.py"]

FROM builder as dev-envs

RUN apk update
RUN apk add git

RUN addgroup -S docker
RUN adduser -S --shell /bin/bash --ingroup docker vscode

# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD ["python3", "app.py"]
