FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder

WORKDIR /src
COPY requirements.txt /src
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . .
RUN pip install emoji
CMD ["python3", "app.py"]

FROM builder as dev-envs

RUN apk update
RUN apk add git
# nano для траблшутинга
RUN apk add nano 

RUN addgroup -S docker
RUN adduser -S --shell /bin/bash --ingroup docker vscode

# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD ["python3", "app.py"]
