# This is a basic workflow to help you get started with Actions

name: Test-pypline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "ZooparkFlask" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Teting
        run: echo "Hello world!"
  my_testings:
    runs-on: ubuntu-latest
    steps:
      - name: Tetings2
        run: echo "Hello Sego!"
